version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "20:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    assignees:
      - TheBam1990
    versioning-strategy: increase
